app = "singlestoredb-fly"
kill_signal = "SIGINT"
kill_timeout = 30

[[services]]
  internal_port = 3306
  protocol = "tcp"

  [[services.ports]]
    port = 3306

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.http_checks]]
    grace_period = "30s"
    interval = 10000
    method = "get"
    path = "/ping"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 9000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 9443
